[package]
name = "pars3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
gltf = { version = "1.4.1", features = ["utils"], optional = true }

[features]
f64 = []
gltf = ["dep:gltf"]
